version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./task_db.sql:/docker-entrypoint-initdb.d/task_db.sql
  app:
    build: .
    container_name: gin-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  postgres_data: